# Generated by Django 4.2.6 on 2023-11-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_county_alter_vote_confidence_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='the county where the project is situated in'),
        ),
    ]
