# Generated by Django 4.2.6 on 2023-11-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='about',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
