# Generated by Django 4.2.6 on 2023-11-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_project_approved'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='approved',
        ),
    ]
