# Generated by Django 4.2.6 on 2023-11-29 14:31

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.upload_to),
        ),
    ]
