# Generated by Django 4.2.6 on 2024-01-15 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0023_project_likes_delete_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
