# Generated by Django 4.2.6 on 2024-01-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_project_likes_count_alter_project_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='likes_count',
        ),
    ]
